# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateCrossingPercentage <- function(Cx, Cy, Ax, Ay, Bx, By, R) {
    .Call('_recurse_calculateCrossingPercentage', PACKAGE = 'recurse', Cx, Cy, Ax, Ay, Bx, By, R)
}

getIsNewTrack <- function(trajId) {
    .Call('_recurse_getIsNewTrack', PACKAGE = 'recurse', trajId)
}

getRecursionsCpp <- function(trajX, trajY, trajT, trajId, locX, locY, radius, threshold, timeunits, verbose) {
    .Call('_recurse_getRecursionsCpp', PACKAGE = 'recurse', trajX, trajY, trajT, trajId, locX, locY, radius, threshold, timeunits, verbose)
}

